[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tet4d"
version = "0.7.5"
description = "tet4d"
requires-python = ">=3.11"
dependencies = [
  "pygame-ce",
]

[project.optional-dependencies]
dev = [
  "pytest",
  "ruff==0.16.0",
  "scons==4.10.1",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["tet4d*"]

[tool.ruff]
line-length = 88
extend-exclude = [
  "native/third_party",
]

[tool.ruff.lint]
extend-select = [
  "C901",
]
