from __future__ import annotations

import argparse
import difflib
import hashlib
import json
import shutil
import sys
import tempfile
from pathlib import Path
from typing import Any

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from tools.migration.trace_schema import (
    SCHEMA_VERSION,
    TRACE_VERSION,
    canonical_json,
    generator_metadata,
    read_json,
    stable_hash,
    write_canonical_json,
)


BUNDLE_VERSION = 1
DEFAULT_BUNDLE_OUT = Path("migration/exported_bundle")
PROJECT_NAME = "tet4d"
README_TEXT = """# tet4d Migration Bundle

This directory is generated by `tools/migration/export_config_bundle.py`.
It is a disposable migration artifact, not a source of truth.

Python remains the semantic oracle. Authoritative config stays under
`config/`, authoritative traces stay under `migration/golden_traces/`, and
authority docs stay in `docs/` plus `CURRENT_STATE.md`.

Unity/Godot replay spikes should consume this bundle as input data for trace
replay before implementing independent topology, gameplay, or endgame logic.
Engine scene, inspector, or project defaults must not replace the Python/config
authorities.

Regenerate and check with:

```bash
PYTHONPATH=src .venv/bin/python tools/migration/export_config_bundle.py --out migration/exported_bundle
PYTHONPATH=src .venv/bin/python tools/migration/export_config_bundle.py --check
PYTHONPATH=src .venv/bin/python tools/migration/compare_config_bundle.py migration/exported_bundle
```
"""

AUTHORITY_DOCS: tuple[tuple[str, str, str], ...] = (
    ("CURRENT_STATE.md", "restart_handoff", "Current migration and handoff state."),
    ("docs/BACKLOG.md", "backlog", "Active migration follow-up tracker."),
    (
        "docs/PROJECT_STRUCTURE.md",
        "project_structure",
        "Generated package layout and source-of-truth inventory.",
    ),
    (
        "docs/rds/RDS_TETRIS_GENERAL.md",
        "product_requirements",
        "Shared topology/gameplay/endgame product requirements.",
    ),
    (
        "docs/rds/RDS_MENU_STRUCTURE.md",
        "menu_requirements",
        "Menu/config authority for launcher, settings, and keybindings.",
    ),
    (
        "docs/plans/topology_playground_current_authority.md",
        "topology_authority",
        "Frozen topology lab semantics and migration boundary.",
    ),
    (
        "docs/plans/topology_gameplay_trace_export.md",
        "trace_authority",
        "Stage 2 topology/gameplay trace oracle contract.",
    ),
    (
        "docs/plans/endgame_trace_export.md",
        "endgame_trace_authority",
        "Stage 3 endgame trace oracle contract.",
    ),
    (
        "docs/plans/migration_config_bundle.md",
        "migration_bundle_authority",
        "Stage 4 generated config bundle and packaging boundary contract.",
    ),
    (
        "docs/plans/godot_trace_replay_spike.md",
        "godot_replay_authority",
        "Stage 6 Godot replay shell and runtime bundle boundary contract.",
    ),
    (
        "docs/plans/godot_core_port_plan.md",
        "godot_core_port_authority",
        "Stage 7+ Godot shell and native core-port ordering authority.",
    ),
    (
        "docs/plans/plain_2d_core_parity_contract.md",
        "plain_2d_core_parity_authority",
        "Accepted plain bounded 2D native trace parity contract.",
    ),
    (
        "docs/plans/plain_nd_core_parity_plan.md",
        "plain_nd_core_parity_authority",
        "Stage 14 plain bounded 3D/4D native trace parity plan.",
    ),
)

CONFIG_CATEGORY_PREFIXES: tuple[tuple[str, str], ...] = (
    ("config/project/", "project_governance"),
    ("config/menu/", "menu_defaults"),
    ("config/keybindings/", "keybinding_defaults"),
    ("config/topology/", "topology_defaults"),
    ("config/gameplay/", "gameplay_defaults"),
    ("config/audio/", "audio_defaults"),
    ("config/help/", "help_defaults"),
    ("config/tutorial/", "tutorial_defaults"),
    ("config/playbot/", "playbot_defaults"),
    ("config/ui/", "ui_defaults"),
)


def _repo_path(path: Path) -> str:
    return path.as_posix()


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def file_sha256(path: Path) -> str:
    return _sha256_bytes(path.read_bytes())


def _copy_file(source: Path, target: Path) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, target)


def _iter_config_source_paths() -> tuple[Path, ...]:
    paths: list[Path] = []
    for path in Path("config").rglob("*"):
        if not path.is_file():
            continue
        if "__pycache__" in path.parts or path.name == ".DS_Store":
            continue
        if path.parts[:2] == ("config", "schema"):
            continue
        if path.suffix not in {".json", ".txt"}:
            continue
        paths.append(path)
    return tuple(sorted(paths, key=_repo_path))


def _iter_schema_paths() -> tuple[Path, ...]:
    return tuple(
        sorted(path for path in Path("config/schema").glob("*.json") if path.is_file())
    )


def _iter_trace_paths(trace_type: str) -> tuple[Path, ...]:
    root = Path("migration/golden_traces") / trace_type
    return tuple(sorted(root.glob("*.json"), key=_repo_path))


def _config_category(path: Path) -> str:
    path_text = _repo_path(path)
    for prefix, category in CONFIG_CATEGORY_PREFIXES:
        if path_text.startswith(prefix):
            return category
    return "config"


def _json_or_text_payload(path: Path) -> dict[str, Any]:
    if _repo_path(path) == "config/project/policy_pack.json":
        return {
            "format": "json",
            "payload_included": False,
            "payload_omitted_reason": (
                "Governance policy pack is indexed by digest; source file remains "
                "the machine-readable authority."
            ),
        }
    if path.suffix == ".json":
        return {"format": "json", "payload": read_json(path), "payload_included": True}
    return {
        "format": "text",
        "payload": path.read_text(encoding="utf-8"),
        "payload_included": True,
    }


def _config_source_entries() -> dict[str, dict[str, Any]]:
    entries: dict[str, dict[str, Any]] = {}
    for path in _iter_config_source_paths():
        payload = _json_or_text_payload(path)
        entries[_repo_path(path)] = {
            "category": _config_category(path),
            "sha256": file_sha256(path),
            **payload,
        }
    return entries


def _trace_metadata(trace_type: str, source_path: Path) -> dict[str, Any]:
    payload = read_json(source_path)
    final = payload.get("final", {}) if isinstance(payload.get("final"), dict) else {}
    topology_payload = (
        payload.get("topology", {}) if isinstance(payload.get("topology"), dict) else {}
    )
    return {
        "trace_type": str(payload.get("trace_type", trace_type)),
        "case_id": str(payload.get("case_id", source_path.stem)),
        "path": f"traces/{trace_type}/{source_path.name}",
        "source_path": _repo_path(source_path),
        "sha256": file_sha256(source_path),
        "dimension": payload.get("dimension"),
        "topology_id": payload.get("topology_id", topology_payload.get("topology_id")),
        "topology_preset": payload.get("topology_preset"),
        "frame_count": len(payload.get("frames", [])),
        "final_state_hash": final.get("state_hash"),
        "trace_version": payload.get("trace_version"),
    }


def build_trace_index() -> dict[str, list[dict[str, Any]]]:
    return {
        trace_type: [
            _trace_metadata(trace_type, path) for path in _iter_trace_paths(trace_type)
        ]
        for trace_type in ("topology", "gameplay", "endgame")
    }


def _schema_purpose(path: Path) -> str:
    name = path.stem.replace("_", " ").replace("-", " ")
    return f"{name} JSON schema"


def build_schema_index() -> dict[str, Any]:
    files = [
        {
            "source_path": _repo_path(path),
            "sha256": file_sha256(path),
            "purpose": _schema_purpose(path),
        }
        for path in _iter_schema_paths()
    ]
    return {
        "bundle_version": BUNDLE_VERSION,
        "trace_schema": {
            "source_path": "tools/migration/trace_schema.py",
            "schema_version": SCHEMA_VERSION,
            "trace_version": TRACE_VERSION,
            "sha256": file_sha256(Path("tools/migration/trace_schema.py")),
            "purpose": "Code-defined canonical trace schema helpers.",
        },
        "files": files,
    }


def build_authority_index() -> dict[str, Any]:
    files = [
        {
            "source_path": source_path,
            "sha256": file_sha256(Path(source_path)),
            "role": role,
            "purpose": purpose,
        }
        for source_path, role, purpose in AUTHORITY_DOCS
    ]
    return {
        "bundle_version": BUNDLE_VERSION,
        "files": files,
    }


def _combined_digest(entries: dict[str, dict[str, Any]]) -> str:
    return stable_hash(
        {path: {"sha256": entry["sha256"]} for path, entry in sorted(entries.items())}
    )


def build_config_bundle(trace_index: dict[str, list[dict[str, Any]]]) -> dict[str, Any]:
    source_files = _config_source_entries()
    schema_index = build_schema_index()
    return {
        "bundle_type": "tet4d_config_snapshot",
        "bundle_version": BUNDLE_VERSION,
        "authority": {
            "exported_bundle_is_authority": False,
            "python_semantic_oracle": True,
            "source_config_root": "config/",
        },
        "versions": {
            "bundle_version": BUNDLE_VERSION,
            "trace_version": TRACE_VERSION,
            "trace_schema_version": SCHEMA_VERSION,
        },
        "source_files": source_files,
        "source_file_digests": {
            path: entry["sha256"] for path, entry in sorted(source_files.items())
        },
        "combined_digest": _combined_digest(source_files),
        "schema_files": schema_index["files"],
        "trace_index": trace_index,
        "classified_sources": {
            category: [
                path
                for path, entry in sorted(source_files.items())
                if entry["category"] == category
            ]
            for category in sorted(
                {entry["category"] for entry in source_files.values()}
            )
        },
    }


def build_manifest(
    *,
    trace_index: dict[str, list[dict[str, Any]]],
    config_bundle: dict[str, Any],
    schema_index: dict[str, Any],
    authority_index: dict[str, Any],
) -> dict[str, Any]:
    return {
        "bundle_type": "tet4d_migration_bundle",
        "bundle_version": BUNDLE_VERSION,
        "generator": generator_metadata("export_config_bundle"),
        "project": {
            "name": PROJECT_NAME,
        },
        "authority": {
            "python_semantic_oracle": True,
            "exported_bundle_is_authority": False,
            "config_authority_root": "config/",
            "trace_authority_root": "migration/golden_traces/",
            "runtime_semantics_authority": "src/",
        },
        "traces": trace_index,
        "config": {
            "files": [
                {
                    "path": path,
                    "sha256": entry["sha256"],
                    "category": entry["category"],
                }
                for path, entry in sorted(config_bundle["source_files"].items())
            ],
            "combined_digest": config_bundle["combined_digest"],
            "bundle_path": "config/tet4d_config_bundle.json",
        },
        "schemas": {
            "files": schema_index["files"],
            "trace_schema": schema_index["trace_schema"],
            "index_path": "schemas/schema_index.json",
        },
        "docs": {
            "authority_files": authority_index["files"],
            "index_path": "docs/authority_index.json",
        },
        "verification": {
            "compare_trace_required": True,
            "config_bundle_check_required": True,
            "trace_compare_command": (
                "PYTHONPATH=src .venv/bin/python "
                "tools/migration/compare_trace.py migration/golden_traces"
            ),
            "bundle_check_command": (
                "PYTHONPATH=src .venv/bin/python "
                "tools/migration/export_config_bundle.py --check"
            ),
        },
    }


def _write_readme(path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(README_TEXT, encoding="utf-8")
    return path


def export_bundle(out_dir: Path) -> list[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    trace_index = build_trace_index()
    schema_index = build_schema_index()
    authority_index = build_authority_index()
    config_bundle = build_config_bundle(trace_index)
    manifest = build_manifest(
        trace_index=trace_index,
        config_bundle=config_bundle,
        schema_index=schema_index,
        authority_index=authority_index,
    )

    written = [
        write_canonical_json(out_dir / "manifest.json", manifest),
        write_canonical_json(
            out_dir / "config" / "tet4d_config_bundle.json",
            config_bundle,
        ),
        write_canonical_json(
            out_dir / "docs" / "authority_index.json", authority_index
        ),
        write_canonical_json(out_dir / "schemas" / "schema_index.json", schema_index),
        _write_readme(out_dir / "README.md"),
    ]
    for trace_type, entries in trace_index.items():
        for entry in entries:
            source = Path(str(entry["source_path"]))
            target = out_dir / str(entry["path"])
            _copy_file(source, target)
            written.append(target)
    return written


def _bundle_files(root: Path) -> dict[str, Path]:
    return {
        path.relative_to(root).as_posix(): path
        for path in sorted(root.rglob("*"))
        if path.is_file()
    }


def _file_text(path: Path) -> str:
    if path.suffix == ".json":
        return canonical_json(json.loads(path.read_text(encoding="utf-8")))
    return path.read_text(encoding="utf-8")


def compare_bundle_directory(path: Path) -> list[str]:
    failures: list[str] = []
    with tempfile.TemporaryDirectory(prefix="tet4d-config-bundle-") as raw_tmp:
        tmp_root = Path(raw_tmp) / "bundle"
        export_bundle(tmp_root)
        expected_files = _bundle_files(path)
        regenerated_files = _bundle_files(tmp_root)
        expected_names = set(expected_files)
        regenerated_names = set(regenerated_files)
        for name in sorted(regenerated_names - expected_names):
            failures.append(f"missing checked-in bundle file: {path / name}")
        for name in sorted(expected_names - regenerated_names):
            failures.append(f"extra checked-in bundle file: {path / name}")
        for name in sorted(expected_names & regenerated_names):
            expected_text = _file_text(expected_files[name])
            regenerated_text = _file_text(regenerated_files[name])
            if expected_text == regenerated_text:
                continue
            diff = "".join(
                difflib.unified_diff(
                    expected_text.splitlines(keepends=True),
                    regenerated_text.splitlines(keepends=True),
                    fromfile=str(expected_files[name]),
                    tofile=f"regenerated/{name}",
                )
            )
            failures.append(diff)
    return failures


def check_bundle(path: Path) -> int:
    failures = compare_bundle_directory(path)
    if failures:
        for failure in failures:
            print(failure)
        return 1
    print(f"config bundle comparison passed: {path}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Export the generated tet4d migration config bundle."
    )
    parser.add_argument("--out", type=Path, default=DEFAULT_BUNDLE_OUT)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args(argv)
    if args.check:
        return check_bundle(args.out)
    paths = export_bundle(args.out)
    if not args.quiet:
        for path in paths:
            print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
